version: '3'
services:
    php:
      container_name: php
      build:
        context: .
        dockerfile: php/Dockerfile
      networks:
        - myapp_net
      depends_on:
        - mysql-custom
    nginx-front:
      container_name: nginx-front
      build:
        context: .
        dockerfile: nginx/Dockerfile
      ports: 
        - "8080:80"
      networks:
        - myapp_net
      depends_on:
        - php
    mysql-custom:
      container_name: mysql-custom
      image: mysql-custom
      volumes:
        - mysql-volume:/var/lib/mysql
      networks:
        - myapp_net

volumes:
   mysql-volume:
networks:
   myapp_net: 
